#!/usr/bin/env python3
"""
check-config-sourcing.py — a config file must never be sourced by a root script.

WHY THIS EXISTS

`wasp-offsite-backup.sh` read /etc/wp-install/offsite.conf with `. "$CONF"`,
which EXECUTES it. Every line ran as root, on every backup, every night.
Anything able to write that file -- a path traversal, a careless chmod, a
compromised process wanting persistence -- got root code execution on the next
cron tick, from a file nobody thinks of as executable.

The Linux kernel made the same change for the same reason: "Don't source the
kernel config file in shell scripts. The config file is not a shell script."

The commonly-suggested middle ground -- grep for NAME=VALUE then source the
filtered copy -- is not sufficient, and the Bash Hackers Wiki says so plainly:
it "doesn't prevent all methods of code execution".

WHAT IT CHECKS

Any `.` or `source` of a path ending .conf/.cfg/.ini/.env in payload/bin.
Sourcing vars.sh and pinned.env is exempt: those are generated by the installer
from validated input and are part of the trust base, not operator-editable
configuration.
"""

import glob
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# `. path` or `source path` where path looks like a config file.
SOURCING = re.compile(
    r'^[^#\n]*(?:^|\s|;|&&|\|\|)(?:\.|source)\s+"?\$?\{?[A-Za-z0-9_/${}.-]*'
    r'\.(conf|cfg|ini|env)"?', re.M)

# Generated by the installer from validated input, root-owned 0600, and never
# presented to an operator as something to edit. These are part of the trust
# base rather than configuration.
#
# The distinction that matters is not the file extension, it is WHO WRITES IT.
# offsite.conf was written from operator input at runtime AND documented as
# editable — so write access to it was a realistic path, and sourcing it turned
# that into root code execution. These three are produced once by the installer
# and touched by nobody.
#
# That is a weaker guarantee than not sourcing at all, and it is recorded as
# such: if any of these ever becomes operator-editable, it must be parsed, not
# sourced. Worth revisiting if the trust base ever widens.
EXEMPT = ("pinned.env", "vars.sh", "wp-run-extra.env")


def scan(path):
    out = []
    for n, line in enumerate(open(path, encoding="utf-8", errors="replace")
                             .read().split("\n"), 1):
        if line.lstrip().startswith("#"):
            continue
        if any(e in line for e in EXEMPT):
            continue
        if SOURCING.match(line):
            out.append((n, line.strip()[:70]))
    return out


def self_test():
    import tempfile
    with tempfile.NamedTemporaryFile("w", suffix=".sh", delete=False) as f:
        f.write('. "$CONF.conf"\n'); bad = f.name
    assert scan(bad), "self-test: sourced config not detected"
    os.unlink(bad)
    with tempfile.NamedTemporaryFile("w", suffix=".sh", delete=False) as f:
        f.write('. /etc/wp-install/pinned.env\n'); ok = f.name
    assert not scan(ok), "self-test: exempt file flagged"
    os.unlink(ok)
    return True


def main():
    self_test()
    files = sorted(glob.glob(os.path.join(REPO, "payload", "bin", "*.sh")))
    problems = []
    for p in files:
        for n, line in scan(p):
            problems.append(f"{os.path.relpath(p, REPO)}:{n}: {line}")
    if problems:
        print(f"FOUND {len(problems)} config file(s) being SOURCED:")
        for x in problems:
            print(f"  {x}")
        print()
        print("  Sourcing executes the file. A root script reading an")
        print("  operator-editable config this way turns write access into")
        print("  root code execution. Parse it line by line instead.")
        return 1
    print(f"Config sourcing: CLEAN — {len(files)} tools, no config file is executed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
