#!/usr/bin/env bash
# 05-ssh-and-network-inject.sh — part of install.sh (host-side, runs on the Proxmox VE host).
# Injects hostname, SSH hardening config, admin credentials file, nftables.nft, and /etc/network/interfaces onto the mounted disk.
# Sourced by install.sh in order -- do not run this file directly; it
# depends on variables and functions (msg_*, TMPDIR, REPO_DIR, MNT, etc.)
# that install.sh and earlier lib files set up.

echo "$HN" > "$MNT/etc/hostname"
grep -q "$HN" "$MNT/etc/hosts" 2>/dev/null || echo "127.0.1.1  $HN" >> "$MNT/etc/hosts"

# ─ SSH hardening ──────────────────────────────────────────────────────────────
SSHCFG="$MNT/etc/ssh/sshd_config"; mkdir -p "$MNT/etc/ssh"
[[ $DISABLE_PW_AUTH -eq 1 ]] && _PWAUTH="no" || _PWAUTH="yes"

# FORENSIC FIX (new-audit Critical finding, confirmed accurate): root SSH
# login used to re-enable itself as a "fallback" when admin-account
# creation failed (ADMIN_USER_CREATED=0). Removed: PermitRootLogin is now
# unconditionally "no". Recovery when the admin account is missing is via
# the Proxmox console (`qm terminal <vmid>`, which uses the ROOT_PASS set
# unconditionally in 04-nbd-mount-and-chroot.sh) — not by exposing root
# over the network, which is a worse trade for a rare failure case.
_ROOTLOGIN="no"

if [[ "$ADMIN_USER_CREATED" -eq 1 ]]; then
  # Normal path: the admin account (wheel + doas, created in the chroot
  # above) is the only way in.
  ADMIN_HASHED=$(openssl passwd -6 "$ADMIN_PASS")
  sed -i "s|^${ADMIN_USER}:[^:]*:|${ADMIN_USER}:${ADMIN_HASHED}:|" "$MNT/etc/shadow"
  if [[ -n "$SSH_KEYS" ]]; then
    mkdir -p "$MNT/home/${ADMIN_USER}/.ssh"
    echo "$SSH_KEYS" > "$MNT/home/${ADMIN_USER}/.ssh/authorized_keys"
    chmod 700 "$MNT/home/${ADMIN_USER}/.ssh"
    chmod 600 "$MNT/home/${ADMIN_USER}/.ssh/authorized_keys"
    chown -R "${ADMIN_UID}:${ADMIN_GID}" "$MNT/home/${ADMIN_USER}"
  fi
else
  # FALLBACK — should be rare, adduser is a simple local-filesystem
  # operation with no network dependency. Root SSH stays disabled either
  # way now, so there's nothing useful to do with an operator-supplied SSH
  # key here — it would sit on an account (root) that SSH can never reach.
  # This is a degraded state, not a final one — flagged loudly here and
  # again in the closing summary; fix by hand after boot via the console
  # (`qm terminal <vmid>`): adduser, addgroup <user> wheel, apk add doas,
  # echo 'permit persist :wheel' > /etc/doas.d/doas.conf, then copy the
  # intended key into that account's ~/.ssh/authorized_keys yourself.
  :
fi

cat > "$SSHCFG" << SSHEOF
PermitRootLogin ${_ROOTLOGIN}
PasswordAuthentication ${_PWAUTH}
PubkeyAuthentication yes
PermitEmptyPasswords no
MaxAuthTries 6
LoginGraceTime 20
ClientAliveInterval 300
ClientAliveCountMax 2
AllowTcpForwarding no
AllowAgentForwarding no
X11Forwarding no
PermitTunnel no
IgnoreRhosts yes
HostbasedAuthentication no
AllowUsers ${ADMIN_USER}
Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr
KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
SSHEOF
chmod 600 "$SSHCFG"

if [[ "$ADMIN_USER_CREATED" -eq 1 ]]; then
  msg_ok "SSH: ${ADMIN_USER} ($([[ $DISABLE_PW_AUTH -eq 1 ]] && echo 'key-only' || echo 'password')), root login disabled"
else
  msg_warn "SSH: no admin account — SSH has no usable login until you create one (root login stays disabled; see console-recovery instructions above)"
fi

# ─ Admin credentials note (only what the operator doesn't already know) ──────
# ROOT_PASS is never written to disk in plaintext (the operator typed it, no
# need to also leave a copy lying around) — same treatment here. The
# operator-chosen admin password (no-key path) is likewise never written.
# The AUTO-GENERATED admin password (key-provided path, used only by doas —
# see the SSH access prompt) is the one exception: nobody typed it, so
# without writing it down it would be permanently unusable, exactly like the
# openssl-rand DB passwords already documented in /root/.wp-credentials.
if [[ "$ADMIN_USER_CREATED" -eq 1 ]]; then
  if [[ -n "$SSH_KEYS" ]]; then
    cat > "$MNT/root/.wp-admin-credentials" << ADMINCREDS
# ============================================================
# Admin account — generated by create-wordpress-vm.sh
# chmod 600 /root/.wp-admin-credentials
# ============================================================
# Username : ${ADMIN_USER}
# SSH      : key-only (the public key supplied during provisioning)
# Password : ${ADMIN_PASS}
#   Not used for SSH (password login is disabled) — only for 'doas'
#   once logged in, or as a local-console recovery password.
# doas     : any command as root, e.g.  doas -s   (interactive root shell)
# ============================================================
ADMINCREDS
  else
    cat > "$MNT/root/.wp-admin-credentials" << ADMINCREDS
# ============================================================
# Admin account — generated by create-wordpress-vm.sh
# chmod 600 /root/.wp-admin-credentials
# ============================================================
# Username : ${ADMIN_USER}
# SSH      : password (the one set during provisioning)
# doas     : any command as root, e.g.  doas -s   (interactive root shell)
# ============================================================
ADMINCREDS
  fi
  chmod 600 "$MNT/root/.wp-admin-credentials"
  msg_ok "/root/.wp-admin-credentials written (chmod 600)"
fi

# ─ nftables ───────────────────────────────────────────────────────────────────
echo "$NFT_CONF" > "$MNT/etc/nftables.nft"; chmod 600 "$MNT/etc/nftables.nft"

# Persistence for operator-added egress ports. `wp-hardening.sh egress-allow`
# applies a port to the LIVE ruleset and appends an `add element` line here;
# this include is what makes it survive a reboot. Created empty (comments
# only) at install because nftables treats a missing include as a fatal
# error -- and a fatal error loading nftables means the VM boots with NO
# firewall at all, which is a far worse outcome than the feature not working.
mkdir -p "$MNT/etc/wp-install"
cat > "$MNT/etc/wp-install/egress-extra.nft" << 'EGRESSEXTRA'
# Operator-added egress ports, managed by:
#   wp-hardening.sh egress-allow <port> [tcp|udp]
#   wp-hardening.sh egress-deny  <port> [tcp|udp]
# Included from /etc/nftables.nft. Do not delete this file — an empty one is
# valid and expected; a missing one makes the whole ruleset fail to load.
EGRESSEXTRA
chmod 644 "$MNT/etc/wp-install/egress-extra.nft"
printf '\ninclude "/etc/wp-install/egress-extra.nft"\n' >> "$MNT/etc/nftables.nft"
msg_ok "nftables.nft injected (with egress-extra include)"

# ─ Network addressing (DHCP or static) ────────────────────────────────────────
# Alpine's cloud image reads /etc/network/interfaces via the OpenRC "networking"
# service (already enabled below). We overwrite it unconditionally so behaviour
# is deterministic regardless of what the base image shipped with.
mkdir -p "$MNT/etc/network"
if [[ "$NET_MODE" == "static" ]]; then
  IFS=' ' read -r -a _dns_arr <<< "$VM_DNS"
  cat > "$MNT/etc/network/interfaces" << IFACEEOF
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address ${VM_STATIC_IP}
    netmask ${VM_NETMASK}
    gateway ${VM_GATEWAY}
    dns-nameservers ${_dns_arr[*]}
IFACEEOF
  msg_ok "Static network config injected: ${VM_STATIC_IP}/${VM_PREFIX} via ${VM_GATEWAY}"
else
  cat > "$MNT/etc/network/interfaces" << 'IFACEEOF'
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
IFACEEOF
  msg_ok "DHCP network config injected"
fi

# ── Shell-safe serialization for vars.sh (BUG FIX v7-12, #10) ──────────────
