#!/usr/bin/env bash
# 06-vars-and-payload-inject.sh — part of install.sh (host-side, runs on the Proxmox VE host).
# Writes /etc/wp-install/vars.sh (shell-safe serialized operator settings), deploys the Apache security config and mod_remoteip files, stages payload/ onto the disk, copies install-wordpress.sh into place, and writes the first-boot launcher.
# Sourced by install.sh in order -- do not run this file directly; it
# depends on variables and functions (msg_*, TMPDIR, REPO_DIR, MNT, etc.)
# that install.sh and earlier lib files set up.

# Every value below that came from free-text operator input (CrowdSec
# enrolment key, GeoIP country lists, MaxMind Account ID / License Key)
# used to be written into this heredoc via plain "${VAR}" interpolation —
# safe only as long as the operator never typed a literal double-quote,
# backtick, or $(...) into any of those prompts. Any of those characters
# would break out of the VAR="..." assignment the moment vars.sh is next
# sourced — which happens as root, during Stage 2 on first boot, and on
# every later run of update.sh / wp-hardening.sh / wp-geoip-setup.sh,
# which all source this file too — turning a typo or a hostile paste into
# arbitrary shell execution. _vars_q() closes this the standard way: wrap
# the value in single quotes, escaping any embedded single quote as '\''
# (close quote, escaped literal quote, reopen quote). This is plain POSIX
# single-quote escaping, deliberately NOT bash's own `printf %q` — %q can
# emit $'...' ANSI-C-quoted output for some inputs, which is not reliably
# parsed by BusyBox ash (this is /bin/sh on the Alpine VM, and what
# update.sh / wp-hardening.sh / wp-geoip-setup.sh all source vars.sh
# under, since their shebang is #!/bin/sh, not #!/bin/bash) — so %q's own
# output could have silently broken the exact file it was meant to make
# safer. The single-quote form is valid POSIX syntax in every
# Bourne-family shell without exception, applied uniformly to every field
# below rather than a per-field judgment call about which ones "need" it.
_vars_q() {
  local q=${1//\'/\'\\\'\'}
  printf "'%s'" "$q"
}

# Write installer variables that can't go in the INSTALLER_EOF heredoc
# (which is single-quoted on the host, so host variables don't expand inside).
# The installer sources this file early in Stage 2.
mkdir -p "$MNT/etc/wp-install"
cat > "$MNT/etc/wp-install/vars.sh" << INSTALLERENV
# WordPress VM installer variables — generated by create-wordpress-vm.sh
# Sourced by /root/install-wordpress.sh during Stage 2, and by update.sh /
# wp-hardening.sh / wp-geoip-setup.sh afterward. Every value below is
# single-quote escaped (see _vars_q in create-wordpress-vm.sh) rather than
# bare interpolation — do not hand-edit with an unescaped value pasted
# back in.
WP_ADMIN_SLUG=$(_vars_q "$WP_ADMIN_SLUG")
CROWDSEC_ENROLL_KEY=$(_vars_q "$CROWDSEC_ENROLL_KEY")
NET_MODE=$(_vars_q "$NET_MODE")
VM_STATIC_IP=$(_vars_q "$VM_STATIC_IP")
GEOIP_ENABLED=$(_vars_q "${GEOIP_ENABLED:-0}")
GEOIP_MODE=$(_vars_q "${GEOIP_MODE:-}")
GEOIP_WHITELIST=$(_vars_q "${GEOIP_WHITELIST:-}")
GEOIP_BLOCKLIST=$(_vars_q "${GEOIP_BLOCKLIST:-}")
MAXMIND_ACCOUNT_ID=$(_vars_q "${MAXMIND_ACCOUNT_ID:-}")
MAXMIND_LICENSE_KEY=$(_vars_q "${MAXMIND_LICENSE_KEY:-}")
USE_DIGEST_PINNING=$(_vars_q "${USE_DIGEST_PINNING:-1}")
DEPLOYMENT_PROFILE=$(_vars_q "${DEPLOYMENT_PROFILE:-production}")
ADMIN_USER=$(_vars_q "$ADMIN_USER")
ADMIN_USER_CREATED=$(_vars_q "${ADMIN_USER_CREATED:-0}")
# v7-16: persist the firewall/proxy values too. These were never written to
# vars.sh, so every tool that sourced it saw them empty — most visibly the
# validator, whose wp-admin check gated on ${ADMIN_CIDR} and therefore always
# reported "No wp-admin IP restriction configured" even when one WAS set in
# the Apache config. Writing them here lets tools display and reason about the
# configured restrictions; the Apache/nftables configs remain the source of
# truth that the validator cross-checks against.
ADMIN_CIDR=$(_vars_q "${ADMIN_CIDR:-}")
ALLOWED_ADMIN_IP=$(_vars_q "${ALLOWED_ADMIN_IP:-}")
INSTALL_CLAMAV=$(_vars_q "${INSTALL_CLAMAV:-0}")
WORDFENCE_FEED=$(_vars_q "${WORDFENCE_FEED:-scanner}")
# Build identity first in the file, so it is the first thing seen in any
# pasted vars.sh.
WASP_VERSION=$(_vars_q "${WASP_VERSION:-unknown}")
WASP_VERSION_NOTE=$(_vars_q "${WASP_VERSION_NOTE:-}")
OFFSITE_AGE_RECIPIENT=$(_vars_q "${OFFSITE_AGE_RECIPIENT:-}")
# S3 secret is NOT written to vars.sh — it goes only into rclone.conf at 0600.
# vars.sh is sourced by several tools and read during troubleshooting; a
# storage credential does not belong somewhere that widely handled.
S3_PROVIDER=$(_vars_q "${S3_PROVIDER:-}")
S3_ENDPOINT=$(_vars_q "${S3_ENDPOINT:-}")
S3_REGION=$(_vars_q "${S3_REGION:-}")
OFFSITE_METHOD=$(_vars_q "${OFFSITE_METHOD:-none}")
OFFSITE_DEST=$(_vars_q "${OFFSITE_DEST:-}")
OFFSITE_RETAIN=$(_vars_q "${OFFSITE_RETAIN:-14}")
OFFSITE_APPEND_ONLY=$(_vars_q "${OFFSITE_APPEND_ONLY:-unknown}")
GOVERNANCE_EMAIL=$(_vars_q "${GOVERNANCE_EMAIL:-}")
EGRESS_PROXY=$(_vars_q "${EGRESS_PROXY:-0}")
PAGE_BUILDER_DOMAINS=$(_vars_q "${PAGE_BUILDER_DOMAINS:-}")
MFA_ENFORCE=$(_vars_q "${MFA_ENFORCE:-0}")
MFA_GRACE_DAYS=$(_vars_q "${MFA_GRACE_DAYS:-7}")
CTI_ENRICH_BANS=$(_vars_q "${CTI_ENRICH_BANS:-0}")
WORDFENCE_API_KEY=$(_vars_q "${WORDFENCE_API_KEY:-}")
CROWDSEC_WHITELIST=$(_vars_q "${CROWDSEC_WHITELIST:-}")
RESTRICT_EGRESS=$(_vars_q "${RESTRICT_EGRESS:-0}")
SMTP_HOST=$(_vars_q "${SMTP_HOST:-}")
SMTP_FAILED_CLOSED=$(_vars_q "${SMTP_FAILED_CLOSED:-0}")
SMTP_PORT=$(_vars_q "${SMTP_PORT:-587}")
SMTP_USER=$(_vars_q "${SMTP_USER:-}")
SMTP_PASS=$(_vars_q "${SMTP_PASS:-}")
SMTP_FROM=$(_vars_q "${SMTP_FROM:-}")
SMTP_FROM_NAME=$(_vars_q "${SMTP_FROM_NAME:-}")
SMTP_ENCRYPTION=$(_vars_q "${SMTP_ENCRYPTION:-tls}")
WP_DOMAIN=$(_vars_q "${WP_DOMAIN:-}")
WP_SCHEME=$(_vars_q "${WP_SCHEME:-http}")
WP_SITE_TITLE=$(_vars_q "${WP_SITE_TITLE:-}")
WP_ADMIN_EMAIL=$(_vars_q "${WP_ADMIN_EMAIL:-}")
PROXY_IP=$(_vars_q "${PROXY_IP:-}")
SSH_CIDR=$(_vars_q "${SSH_CIDR:-}")
WEB_CIDR=$(_vars_q "${WEB_CIDR:-}")
INSTALLERENV
chmod 600 "$MNT/etc/wp-install/vars.sh"
msg_ok "Installer vars injected (slug=${WP_ADMIN_SLUG:-default}, cs-enroll=${CROWDSEC_ENROLL_KEY:+provided}, net=${NET_MODE}, geoip=${GEOIP_ENABLED:-0}, digest-pin=${USE_DIGEST_PINNING:-1}, admin=${ADMIN_USER})"

# ─ Apache security config (host-built, CIDRs/IPs already substituted) ─────────
# The installer reads this from /root/wp-security.conf and copies it to the
# correct bind-mount path. This is the same pattern as nftables injection.
printf '%s\n' "$APACHE_SECURITY_CONF" > "$MNT/root/wp-security.conf"
chmod 644 "$MNT/root/wp-security.conf"
msg_ok "wp-security.conf injected (admin: ${ADMIN_CIDR:-open}, extra-ip: ${ALLOWED_ADMIN_IP:-none})"

# ─ mod_remoteip files (only if PROXY_IP was set) ─────────────────────────────
if [[ -n "$PROXY_IP" ]]; then
  cat > "$MNT/root/wp-remoteip.load" << RILOAD
LoadModule remoteip_module /usr/lib/apache2/modules/mod_remoteip.so
RILOAD
  cat > "$MNT/root/wp-remoteip.conf" << RICONF
RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy ${PROXY_IP}
RICONF
  chmod 644 "$MNT/root/wp-remoteip.load" "$MNT/root/wp-remoteip.conf"
  msg_ok "mod_remoteip files injected (trusted proxy: ${PROXY_IP})"
fi

# ─ Stage payload/ onto the VM disk (NEW -- replaces per-file heredocs) ───────
# install-wordpress.sh and its stage files (payload/stages/) now read their
# static content from real files instead of regenerating it from a heredoc
# each install. Everything under payload/, except install-wordpress.sh and
# stages/ (copied to their own dedicated locations below), lands at
# PAYLOAD_DIR; the stage files land at STAGE_DIR.
mkdir -p "$MNT/etc/wp-install/payload" "$MNT/etc/wp-install/stages"
for _p in "${REPO_DIR}"/payload/*/; do
  _name=$(basename "$_p")
  [ "$_name" = "stages" ] && continue
  cp -a "$_p" "$MNT/etc/wp-install/payload/$_name"
done
cp -a "${REPO_DIR}/payload/stages/." "$MNT/etc/wp-install/stages/"

# Copy the signed manifest and the release key onto the VM. This is not for
# the install -- install.sh already verified them on the host. It is so the
# VM can re-verify its own tooling MONTHS later, which is the more valuable
# use: it detects an attacker who got root on the VM and edited update.sh or
# wp-hardening.sh to disable a control or hide their presence. Release
# integrity is a one-off; tamper-evidence on a live host is continuous.
if [[ -f "${REPO_DIR}/MANIFEST.sha256" ]]; then
  cp -a "${REPO_DIR}/MANIFEST.sha256" "$MNT/etc/wp-install/" 2>/dev/null || true
  [[ -f "${REPO_DIR}/MANIFEST.sha256.minisig" ]] && \
    cp -a "${REPO_DIR}/MANIFEST.sha256.minisig" "$MNT/etc/wp-install/" 2>/dev/null || true
  printf '%s\n' "${WASP_PUBKEY:-}" > "$MNT/etc/wp-install/release.pub"
  chmod 644 "$MNT/etc/wp-install/MANIFEST.sha256" "$MNT/etc/wp-install/release.pub" 2>/dev/null || true
  msg_ok "Signed manifest staged for on-VM integrity checking"
fi

# CTI key goes only into its own 0600 file, never vars.sh -- vars.sh is
# sourced by several tools and read during troubleshooting, and an API
# credential does not belong somewhere that widely handled.
if [[ -n "${CTI_API_KEY:-}" ]]; then
  {
    printf 'CTI_API_KEY=%s\n'         "$CTI_API_KEY"
    printf 'CTI_MONTHLY_BUDGET=%s\n'  "${CTI_MONTHLY_BUDGET:-120}"
    printf 'CTI_ENRICH_BANS=%s\n'     "${CTI_ENRICH_BANS:-0}"
  } > "$MNT/etc/wp-install/cti.conf"
  chmod 600 "$MNT/etc/wp-install/cti.conf"
  msg_ok "CTI configuration written (0600, root-only)"
fi

# ── Off-VM backup credentials ────────────────────────────────────────────────
# Copied with 0400/0600 root ownership. WordPress runs as uid 33 and cannot
# read them, so a compromise of the web application alone does not reach the
# backup destination -- only a root compromise does, which is exactly why the
# destination should also be append-only.
if [[ "${OFFSITE_METHOD:-none}" != "none" ]]; then
  {
    printf 'OFFSITE_METHOD=%s\n'      "$OFFSITE_METHOD"
    printf 'OFFSITE_DEST=%s\n'        "$OFFSITE_DEST"
    printf 'OFFSITE_RETAIN=%s\n'      "${OFFSITE_RETAIN:-14}"
    printf 'OFFSITE_APPEND_ONLY=%s\n' "${OFFSITE_APPEND_ONLY:-unknown}"
    # The recipient is a PUBLIC key, so it is not a secret; it lives in the
    # same 0600 file purely to keep the off-VM settings in one place.
    printf 'OFFSITE_AGE_RECIPIENT=%s\n' "${OFFSITE_AGE_RECIPIENT:-}"
  } > "$MNT/etc/wp-install/offsite.conf"
  chmod 600 "$MNT/etc/wp-install/offsite.conf"

  if [[ -n "${OFFSITE_KEY_PATH:-}" && -r "$OFFSITE_KEY_PATH" ]]; then
    install -m 0400 "$OFFSITE_KEY_PATH" "$MNT/etc/wp-install/offsite-key"
    # Capture the destination host key NOW, from the Proxmox host, so the VM
    # can use StrictHostKeyChecking=yes rather than trusting whatever answers
    # on first contact. For a backup target, accept-new would mean a MITM
    # could silently receive every database dump.
    _oh="${OFFSITE_DEST#*@}"; _oh="${_oh%%:*}"
    if ssh-keyscan -T 10 "$_oh" > "$MNT/etc/wp-install/offsite-known_hosts" 2>/dev/null \
       && [[ -s "$MNT/etc/wp-install/offsite-known_hosts" ]]; then
      chmod 644 "$MNT/etc/wp-install/offsite-known_hosts"
      msg_ok "Off-VM backup key installed; ${_oh} host key pinned"
    else
      msg_warn "Could not reach ${_oh} to capture its host key."
      msg_warn "  Backups will fail until it is added on the VM:"
      msg_warn "    ssh-keyscan ${_oh} >> /etc/wp-install/offsite-known_hosts"
    fi
  fi
  if [[ "${OFFSITE_METHOD:-}" == "s3" ]]; then
    # Written directly rather than asking the operator to compose rclone
    # config. The remote name is fixed (wasp-s3) so OFFSITE_DEST built at
    # prompt time always resolves.
    {
      printf '[wasp-s3]\n'
      printf 'type = s3\n'
      [[ -n "${S3_PROVIDER:-}" ]] && printf 'provider = %s\n' "$S3_PROVIDER"
      printf 'access_key_id = %s\n'     "$S3_KEY"
      printf 'secret_access_key = %s\n' "$S3_SECRET"
      [[ -n "${S3_ENDPOINT:-}" ]] && printf 'endpoint = %s\n' "$S3_ENDPOINT"
      [[ -n "${S3_REGION:-}" ]]   && printf 'region = %s\n'   "$S3_REGION"
      printf 'acl = private\n'
      printf 'no_check_bucket = true\n'
    } > "$MNT/etc/wp-install/rclone.conf"
    chmod 600 "$MNT/etc/wp-install/rclone.conf"
    msg_ok "rclone S3 configuration written (0600, root-only)"
  fi
  if [[ -n "${OFFSITE_RCLONE_CONF:-}" && -r "$OFFSITE_RCLONE_CONF" ]]; then
    install -m 0600 "$OFFSITE_RCLONE_CONF" "$MNT/etc/wp-install/rclone.conf"
    msg_ok "rclone configuration installed (0600, root-only)"
  fi
fi
chmod -R go-w "$MNT/etc/wp-install/payload" "$MNT/etc/wp-install/stages"
msg_ok "payload/ staged to /etc/wp-install/{payload,stages} ($(find "$MNT/etc/wp-install/payload" "$MNT/etc/wp-install/stages" -type f | wc -l) files)"

# ─ Installer script ───────────────────────────────────────────────────────────
mkdir -p "$MNT/root"
cp "${TMPDIR}/install-wordpress.sh" "$MNT/root/install-wordpress.sh"
chmod +x "$MNT/root/install-wordpress.sh"
[[ -s "$MNT/root/install-wordpress.sh" ]] || msg_error "Installer copy failed."
msg_ok "install-wordpress.sh written ($(wc -l < "$MNT/root/install-wordpress.sh") lines)"

# ─ First-boot launcher ────────────────────────────────────────────────────────
mkdir -p "$MNT/etc/local.d"
cat > "$MNT/etc/local.d/01-wordpress.start" << 'LAUNCH'
#!/bin/sh
[ -f /var/log/wp-install.done ] && exit 0
mkdir -p /var/log
exec sh /root/install-wordpress.sh >> /var/log/wp-install.log 2>&1
LAUNCH
chmod +x "$MNT/etc/local.d/01-wordpress.start"
